# Generated by Django 4.1.3 on 2022-11-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0002_employe_id_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Employe_Id',
        ),
    ]
