# Generated by Django 4.1.3 on 2022-12-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0009_rename_employee_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='current_add',
        ),
    ]
