# Generated by Django 4.1.3 on 2022-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0011_rename_employees_finance_support_sales_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=16)),
                ('product', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lead_source', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
