# Generated by Django 4.1.3 on 2022-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0012_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='email_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
