# Generated by Django 4.1.3 on 2022-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0013_alter_leads_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='email_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
