# Generated by Django 4.1.3 on 2022-12-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0014_alter_leads_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
    ]
