# Generated by Django 4.1.3 on 2022-12-13 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0016_alter_leads_address_alter_leads_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Send_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.finance')),
                ('hr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.hr')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.sales')),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.support')),
            ],
        ),
    ]
