# Generated by Django 4.1.3 on 2022-12-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0017_alter_leads_created_at_send_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_notification',
            name='finance_id',
        ),
        migrations.RemoveField(
            model_name='send_notification',
            name='hr_id',
        ),
        migrations.RemoveField(
            model_name='send_notification',
            name='sales_id',
        ),
        migrations.RemoveField(
            model_name='send_notification',
            name='support_id',
        ),
    ]
