# Generated by Django 4.1.3 on 2022-12-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0018_remove_send_notification_finance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_notification',
            name='finance_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.finance'),
        ),
        migrations.AddField(
            model_name='send_notification',
            name='hr_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.hr'),
        ),
        migrations.AddField(
            model_name='send_notification',
            name='sales_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.sales'),
        ),
        migrations.AddField(
            model_name='send_notification',
            name='support_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.support'),
        ),
    ]
