# Generated by Django 4.1.3 on 2022-12-14 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0019_send_notification_finance_id_send_notification_hr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_notification',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
