# Generated by Django 4.1.3 on 2022-12-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0020_send_notification_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_notification',
            name='admin',
        ),
    ]
