# Generated by Django 4.1.3 on 2022-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0021_remove_send_notification_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
