# Generated by Django 4.1.3 on 2022-12-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0022_send_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_notification',
            name='hr_id',
        ),
        migrations.RemoveField(
            model_name='send_notification',
            name='sales_id',
        ),
        migrations.RemoveField(
            model_name='send_notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='send_notification',
            name='support_id',
        ),
    ]
