# Generated by Django 4.1.3 on 2022-12-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0028_remove_send_notification_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_notification',
            name='support_id',
        ),
    ]
