# Generated by Django 4.1.3 on 2022-12-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0029_remove_send_notification_support_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_notification',
            name='support_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.support'),
        ),
    ]
