# Generated by Django 4.1.3 on 2022-12-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0030_send_notification_support_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_notification',
            name='support_id',
        ),
    ]
