# Generated by Django 4.1.3 on 2022-12-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0032_send_notification_support_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Fin_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('finance_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.finance')),
            ],
        ),
        migrations.CreateModel(
            name='Send_Hr_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('hr_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.hr')),
            ],
        ),
        migrations.CreateModel(
            name='Send_Sale_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('sale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.sales')),
            ],
        ),
        migrations.CreateModel(
            name='Send_Support_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('support_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taggapp.support')),
            ],
        ),
        migrations.DeleteModel(
            name='Send_Notification',
        ),
    ]
