# Generated by Django 4.1.3 on 2022-12-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0033_send_fin_notification_send_hr_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('operator', models.CharField(max_length=100, null=True)),
                ('rates', models.CharField(max_length=100, null=True)),
                ('required', models.CharField(max_length=100, null=True)),
                ('documents', models.CharField(max_length=100, null=True)),
                ('reg_tat', models.CharField(max_length=100, null=True)),
                ('features', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local_Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('operator', models.CharField(max_length=100, null=True)),
                ('rates', models.CharField(max_length=100, null=True)),
                ('required', models.CharField(max_length=100, null=True)),
                ('documents', models.CharField(max_length=100, null=True)),
                ('reg_tat', models.CharField(max_length=100, null=True)),
                ('features', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('operator', models.CharField(max_length=100, null=True)),
                ('rates', models.CharField(max_length=100, null=True)),
                ('required', models.CharField(max_length=100, null=True)),
                ('documents', models.CharField(max_length=100, null=True)),
                ('reg_tat', models.CharField(max_length=100, null=True)),
                ('features', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
