# Generated by Django 4.1.3 on 2022-12-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0034_direct_local_direct_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direct',
            old_name='reg_tat',
            new_name='tat',
        ),
    ]
