# Generated by Django 4.1.3 on 2022-12-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0035_rename_reg_tat_direct_tat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local_direct',
            old_name='reg_tat',
            new_name='tat',
        ),
        migrations.RenameField(
            model_name='sid',
            old_name='reg_tat',
            new_name='tat',
        ),
    ]
