# Generated by Django 4.1.3 on 2022-12-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0036_rename_reg_tat_local_direct_tat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_direct',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
