# Generated by Django 4.1.3 on 2022-12-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0040_alter_direct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
