# Generated by Django 4.1.3 on 2022-12-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0043_alter_direct_created_at_alter_leads_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='local_direct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sid',
            name='created_at',
        ),
    ]
