# Generated by Django 4.1.3 on 2022-12-26 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0044_remove_direct_created_at_remove_leads_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.sales')),
            ],
        ),
    ]
