# Generated by Django 4.1.3 on 2022-12-26 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggapp', '0045_sales_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.support')),
            ],
        ),
        migrations.CreateModel(
            name='HR_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.hr')),
            ],
        ),
        migrations.CreateModel(
            name='Finance_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggapp.finance')),
            ],
        ),
    ]
